name: dsls_app
description: "A Flutter app for dynamic speed limit recommendations and driving safety alerts."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.2.1
  image: ^4.3.0
  provider: ^6.1.2
  geolocator: ^13.0.2
  permission_handler: ^11.4.0
  camera: ^0.11.1
  http: ^1.4.0
  fl_chart: ^0.70.0
  shared_preferences: ^2.2.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  path_provider: ^2.1.0
  vibration: ^2.0.0
  audioplayers: ^6.1.0
  flutter_tts: ^4.2.2
  cupertino_icons: ^1.0.8
  sensors_plus: ^6.1.1
  url_launcher: ^6.2.0
  uuid: ^4.2.0
  encrypt: ^5.0.3
  crypto: ^3.0.3
  flutter_secure_storage: ^9.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/ikayo.png"
flutter:
  uses-material-design: true
  assets:
    - assets/images/ikayo.png
    - assets/sounds/